config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root 'events#index'

  devise_for :users


  resources :users, only: [:index, :show] do
    resources :favorites, only: [:index, :new, :create]
  end

  resources :events, only: [:index] do
    resources :memberships, only: [:index, :new, :create]
  end

  resources :teams, only: [:index]

  resources :games, only: [:index, :create] do
    resources :events, only: [:new, :create, :show]
  end
  post 'games/update_schedule' => 'games#update_schedule', as: :schedule
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_many :teams

  validates :name, presence: true

  CONFERENCES = Conference.all
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
  belongs_to :game

  validates :name,       presence: true
  validates :description, presence: true
  validates :location,   presence: true
  validates :address,    presence: true
  validates :city,      presence: true
  validates :state,     presence: true
  validates :zip,       presence: true

  def full_address
    "#{address} #{city}, #{state} #{zip}"
  end

  def self.search(search)
    if search
      where("name ILIKE ? OR city ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
    end
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :team

  validates :user_id, presence: true
  validates :team_id, presence: true
end

app/models/favorite_teams.rb
class FavoriteTeams < ActiveRecord::Base
  belongs_to :user
  belongs_to :team

  validates :user_id, presence: true
  validates :team_id, presence: true
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :events
  belongs_to :home_team, class_name: "Team", foreign_key: :home_team_id
  belongs_to :away_team, class_name: "Team", foreign_key: :away_team_id

  validates :week, presence: true
  validates :scheduled, presence: true

  def matchup(game)
    "#{game.away_team.name} #{game.away_team.nickname} @ #{game.home_team.name} #{game.home_team.nickname} "
  end

  def format_time(game)
    game.scheduled.in_time_zone('Eastern Time (US & Canada)').strftime('%a %b %d %I:%M %p %Z')
  end

  def self.schedule
    url = "http://api.sportradar.us/ncaafb-t1/2016/REG/schedule.json?api_key=#{ENV['NCAAF_TOKEN']}"
    response = HTTParty.get(url)
    week_number = ''
    scheduled = ''
    home = ''
    away = ''
    network = ''
    response['weeks'].each do |week|
      if week['number'].to_i > 8
        week_number = week['number']
        week['games'].each do |game|
          scheduled = game['scheduled']
          home = game['home']
          away = game['away']
          if game['broadcast']
            network = game['broadcast']['network']
          else
            network = 'none'
          end
          home_team = Team.where(key: home)
          away_team = Team.where(key: away)
          Game.create(week: week_number, scheduled: scheduled, network: network, home_team_id: home_team.ids[0], away_team_id: away_team.ids[0])
        end
      end
    end
    puts "this is your rake task"
  end

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :user_id, presence: true
  validates :event_id, presence: true
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :favorites
  has_many :users, through: :favorites
  has_many :home_games, :class_name => 'Game', :foreign_key => 'home_team_id'
  has_many :away_games, :class_name => 'Game', :foreign_key => 'away_team_id'
  belongs_to :conference

  validates :name, presence: true
  validates :nickname, presence: true
  validates :conference, presence: true
  validates :league, presence: true
  validates :key, presence: true

  def schedule
    Game.where('home_team_id = ? or away_team_id = ?', id, id)
  end

  def full_name
    "#{name} #{nickname}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :memberships
  has_many :events, through: :memberships

  has_many :favorites
  has_many :teams, through: :favorites

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username,:first_name, :last_name, :profile_picture])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authorize_user

  def index
    @events = Event.all
    if user_signed_in?
      @user = current_user
    end
    @favorite_teams = @user.teams
    if params[:search]
      @searched_events = Event.search(params[:search])
      @searched_events.each do |event|
        @game = event.game
      end
    else
      @searched_events = nil
    end
  end

  def show
    @event = Event.find(params[:id])
    @memberships = @event.memberships
    @membership = Membership.new
    @user = current_user
  end

  def new
    if !user_signed_in?
      flash[:notice] = 'Sign in or Sign up to create an event'
      redirect_to root_path
    else
      @event = Event.new
      @game = Game.find(params[:game_id])
    end
  end

  def create
    @game = Game.find(params[:game_id])
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Event added successfully"
      redirect_to game_event_path(@game.id, @event.id)
    else
      flash[:notice] = @event.errors.full_messages.join(", ")
      render 'new'
    end
  end


  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :address, :city, :state, :zip, :game_id)
  end

  def authorize_user
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authorize_user

  def create
    @user = current_user
    @favorites = @user.teams
    @favorite = Favorite.create(user_id: @user.id, team_id: params[:team_id])
    @new_fav_team = @favorite.team
    if @favorite.save
      render json: @new_fav_team.to_json
    end
  end

  private

  def authorize_user
    unless user_signed_in?
      raise ActionController::RoutingError.new('Where ya goin?!@')
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def update_schedule
    ScheduleWorker.perform_async
    render text: "Something is happening"
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :authorize_user

  def create
    @user = current_user
    params[:user_id] = @user.id
    @event = Event.find(params[:event_id])
    @game = @event.game
    @memberships = @event.memberships
    @memberships.each do |membership|
      if membership.user_id == @user.id
        flash[:notice] = 'You are already signed up for this event'
        redirect_to game_event_path(@game, @event)
        return
      end
    end
    @membership = Membership.new(membership_params)
    if @membership.save
      flash[:notice] = 'You have succesfully joined the event'
      redirect_to game_event_path(@game, @event)
    else
      flash[:notice] = @membership.errors.full_messages.join(', ')
      render 'events/show'
    end
  end

  private

  def membership_params
    params.permit(:user_id, :event_id)
  end

  def authorize_user
    unless user_signed_in?
      raise ActionController::RoutingError.new('Where ya goin?!@')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @teams = Team.all
    @favorite = Favorite.new
    @user = User.find(params[:id])
    @favorites = @user.teams
    @conferences = Conference.all
    @conference_collection = Conference::CONFERENCES
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<div class="page-body">
  <div class="content">
    <div id="search-container">
      <h4>Find An Event</h4>
      <div class="search-bar small-12 columns">
        <%= form_tag(events_path, method: :get) do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search by name, city, or description" %>
          <%= submit_tag "Search", class: 'button' %>
          <%= link_to 'Clear Search', events_path %>
        <% end %>
      </div></br></br>
      <% unless @searched_events.nil? %>
        <% @searched_events.each do |event| %>
        <div class="searched-event">
          <h5 class="title"><%= event.name %></h5>
          <ul>
            <li>Where: <%= event.location %></li>
            <li><%= event.full_address %></li>
            <li>When: <%= event.game.format_time(event.game) %></li>
          </ul>
          <div ><%= link_to 'See Details', game_event_path(@game.id, event.id)  %></div>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="games">
      <div class="row game-event">
        <div class="small-4 columns title">
          Your Team's Games
        </div>
        <div class="small-8 columns title">
          Your Team's Events
        </div>
      </div>
      <%@favorite_teams.each do |team|  %>
        <% team.schedule.each do |game| %>
          <div class="row">
            <div class="small-4 columns game">
              <p><%= game.away_team.name %> @ <%= game.home_team.name %></p>
              <p>Time: <%= game.format_time(game) %></p>
              <p>Channel: <%= game.network %></p>
              <button class="event-btn" id="<%=game.id%>" type= "button" name="button" onClick="showEvents()">See Events</button>
              <div><%= link_to 'Create new event', new_game_event_path(game.id) %></div>
            </div>
            <div class="<%=game.id%> small-block-grid-3 events" style="display: none;">
            <% game.events.each do |event| %>
              <div class="small-4 columns event">
                <p><%= event.name %></p>
                <p>Where: <%= event.location %></p>
                <p><%= event.full_address %></p>
                <p>When: <%= event.game.format_time(game)%></p>
                <div id="create-event-link"><%= link_to 'See Details', game_event_path(game.id, event.id)  %></div>
              </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="sign-in-page">
  <div class="wrapper">
    <div class="event-form">
      <h1>Create a new watch event</h1>
      <%= form_for [@game, @event] do |f| %>

        <div>
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>

        <div>
          <%= f.label :description %>
          <%= f.text_area :description %>
        </div>

        <div>
          <%= f.label  :location %>
          <%= f.text_field :location %>
        </div>

        <div>
          <%= f.label :address %>
          <%= f.text_field :address %>
        </div>

        <div>
          <%= f.label :city %>
          <%= f.text_field :city %>
        </div>

        <div>
          <%= f.label  :state %>
          <%= f.text_field :state %>
        </div>
        <div>
          <%= f.label  :zip %>
          <%= f.text_field :zip %>
        </div>
        <div>
          <%= f.hidden_field  :game_id, value: @game.id %>
        </div>

        <div class="actions">
          <%= f.submit "Create it!", class: 'btn' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="page-body">
  <div class="content">
    <div class="event-show profile">
      <h1 class="title">   <%= @event.name %>   </h1><br />
      <ul>
        <li> <%= @event.description %> </li><br />
        <li> <%= @event.location %> </li>
        <li> <%= @event.full_address %> </li>
      </ul>

      <div>
        <%= form_for [@event, @membership] do |f| %>
        <%= f.hidden_field :event_id %>
        <%= f.hidden_field :user_id %>
        <%= f.submit 'Attend', class: 'event-btn' %>
      </div>
      <% end %>

      <div><%=link_to 'Home', root_path, class: 'event-btn'%></div>

      <h4>
        <%= @memberships.length %> fans are attending!
      </h4>
      <ul id="attendees">
        <% @memberships.each do |membership| %>
        <li>
          <%= membership.user.username %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/favorites/new.html.erb
<h1>Add your favorite teams</h1>

<% @conference_collection.each do |conference| %>
  <%= conference.name %>
<button id="<%=conference.name %>" type= "button" name="button" onClick="showTeams()"><%= conference.name %></button>
<div class="<%=conference.name %>" style="display: none;">
  <% conference.teams.each do |team| %>
    <%= team.nickname %>
    <button type="button" name="button" onClick="addTeam()">
      <%= button_to 'Add Team', { controller: 'favorites', action: 'create' }, method: :post, params: { user_id: @user.id, team_id: team.id } %>
    </button>
  <% end %>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="contain-to-grid">
      <nav class="top-bar" data-topbar role="navigation">
        <div >
          <p class="name">Away Games</p>
        </div>
        <section class="top-bar-section">
          <ul class="right">
            <% if user_signed_in? %>
              <li> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> </li>
              <li> <%= link_to 'Your Profile', user_path(current_user) %> </li>
            <% else %>
              <li> <%= link_to 'Sign Up', new_user_registration_path %> </li>
              <li> <%= link_to 'Sign In', new_user_session_path %> </li>
            <% end %>
            <li><%= link_to 'Home', root_path %></li>
          </ul>
       </section>
      </nav>
    </div>
    <% flash.each do |key, value| %>
      <%= value %>
    <% end %>
    <%= yield %>
    <div class ='bottom-bar'>
      <p class = 'copyright'> &copy; Pete Lauring</p>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<div class="page-body">
  <div class = "content">
    <div id="user-bar" class="row">
      <div class="profile small-6 columns">
        <h4> <%= @user.first_name %> <%= @user.last_name %>'s Profile </h4>
        <ul>
          <li><strong>Username:</strong> <%= @user.username %></li>
          <li><strong>Email:</strong> <%= @user.email %></li>
          <li><strong>Member since:</strong> <%= @user.created_at.to_time.strftime('%a %b %d %I:%M %p %Z') %></li>
        </ul>
        <div ><%= link_to 'Edit your profile', edit_user_registration_path, class: 'prof-btn '%></div>
        <div><%= link_to 'Find Games and Events', root_path, class: 'prof-btn'%></div>
      </div>
      <div id="favorites" class="small-6 columns centered">
        <h4>Favorite Teams</h4>
        <% unless @favorites.nil? %>
        <% @favorites.each do |fav| %>
        <li><%= fav.name %> <%= fav.nickname %></li>
        <% end %>
        <% end %>
      </div>
    </div>
    <div id="add-favs" class="row">
      <h4>Add Your Favorite Teams</h4>
      <div class="conferences">
        <% @conferences.each do |conference| %>
          <button id="<%=conference.name %>" class="button" type= "button" name="button" onClick="showTeams()"><%= conference.name %></button>
          <div class="<%=conference.name %>" style="display: none;">
            <% conference.teams.each do |team| %>
              <button class="button secondary" type="button" name="button" onClick="addTeam()" id="<%= team.id %>" data-team="<%= team.id %>" ><%= team.full_name %></button>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>